---
# Description of the xline
xline_json :    '../000_machine_model/xlines/line_bb_for_tracking.json'

# distribution in the normalized xy space
particle_file:  '../001_make_part_distribution/distrib_abc/001.parquet'

# metric
epsn_1     :    2.5e-6   # normalised emittance x
epsn_2     :    2.5e-6   # normalised emittance y
ptau_max   :    27.e-5      # initial off-momentum

# tracking
n_turns    :   1000       # number of turns to track


log_file: 'log.json'
